version: '3.8'

services:
  mysql-products:
    image: mysql:8.0
    container_name: mysql_container_products
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: products
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
